name: Build and Deploy NextJS Test App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build & Push to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 

      - name: Log in to Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set version tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.sha_short }}, ghcr.io/${{ github.repository }}:latest

  deploy:
    name: Deploy to VM
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set version tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      
      - name: SSH into VM and deploy application
        run: |
          ssh -o StrictHostKeyChecking=no \
          -i ~/.ssh/id_rsa \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << EOF
          echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          cd applications/nextjs-app
          docker pull ghcr.io/${{ github.repository }}:latest
          sh deploy.sh
          EOF